# -*- coding: utf-8 -*-
STATS = [
 ('Toast dán thô mã lỗi', '83', "`toast('Lỗi: '+(e.code||e.message))` → người dùng đọc `permission-denied`, `auth/network-request-failed`, `Failed to fetch`"),
 ('Hộp thoại native', '9 + 7', '`confirm()` xoá/khoá/bật quét + `prompt()` nhập số (hạn mức Bright Data, tỷ giá, credit, ngày, Profile ID, tên brand) — hộp thoại trình duyệt, nút OK/Cancel tiếng Anh'),
 ('Tên mục lệch', '3 tên / 1 mục', 'Lead feed · Lead feed realtime · Lead; Hộp việc · Hộp việc hôm nay · Việc; Bảng brand · Bảng brand (agency); Pipeline sales · Pipeline'),
 ('Dấu gạch', '350 vs 44', 'dòng dùng " - " (gạch nối) so với "—"; file mới nhất (45-outreach) dùng "—", file cũ dùng " - " → 2 quy ước sống song song'),
 ('Xưng hô', '3 hệ', '"bạn" 50 dòng · "anh/chị" 14 · "anh"/"em" riêng anh Vinh 12 dòng lọt vào sản phẩm ("VPS của anh", "em tính được số dư", "anh gán vào brand")'),
 ('ALL CAPS gõ tay', '78 cụm', 'nhãn rail feed/ROI/pipeline gõ HOA trực tiếp trong khi CSS đã có 20 rule uppercase → không đổi đồng loạt được; caps nhấn mạnh giữa câu ("KHÔNG thể hoàn tác", "MỌI bài")'),
 ('Emoji trong chuỗi UI', '222', '11/49 tiêu đề card bắt đầu bằng emoji; 16 nút có emoji'),
 ('Ngày giờ', '12 kiểu', '"14:05:33 7/9/2026" · "07/09/26 14:05" · "14:05 · 07/09/2026" · "2m15s" · "12 giây trước"…'),
 ('Tiền tệ', '4 kiểu', '"1,2 tr₫" · "3 tỷ₫" (ký hiệu lai) · "850.000₫" · "$0,0005" (USD với dấu phẩy thập phân)'),
 ('Mô tả dài', '9 câu >120 ký tự', 'câu `.sub` dài nhất 202 ký tự; 14 placeholder >70 ký tự (mất khi gõ); 10 tooltip >90 ký tự chứa hướng dẫn nội bộ ("RAM ~85%", "Safety Score")'),
 ('Lời hứa marketing', '3 chỗ', '"Hệ thống đang trực 24/7 - chưa bỏ sót phút nào" / chip "ĐANG TRỰC 24/7" — có lúc sai sự thật (12 giờ Bright Data ngưng 04/09)'),
 ('Vai tiếng Anh', '48 dòng', '"Super Admin" giữa 4 vai tiếng Việt (Quản trị / Nhân viên sales / Chỉ xem / Chờ duyệt); card hiện "Bạn là Super Admin"'),
]
TOP = [
 ('83 toast lỗi', "'Lỗi: '+(e.code||e.message)", '1 hàm errMsg(e) map mã → câu Việt ("Không có quyền thực hiện", "Mất kết nối, thử lại"); mã kỹ thuật chỉ vào console'),
 ('Banner Pipeline', '"…lưu thật vào Firestore, đồng bộ realtime"', '"Kéo-thả thẻ để đổi giai đoạn — cả đội thấy ngay"'),
 ('16 confirm/prompt', 'hộp thoại trình duyệt', 'modal #modal của app (như form Đã chốt); prompt nhập số → ô input inline'),
 ('Tên mục', 'Lead feed realtime · Hộp việc hôm nay · Bảng brand (agency) · Pipeline sales', 'Lead mới · Hộp việc · Bảng brand · Pipeline — 1 tên duy nhất ở nav, tab dưới, tiêu đề'),
 ('Cấu hình AI Scoring · Keyword & bộ lọc', '', 'Chấm điểm AI · Từ khoá & bộ lọc'),
 ('Chip trạng thái quét', '"ĐANG TRỰC 24/7 – chưa bỏ sót phút nào"', '"Quét tự động · 3 phút/lượt · lần cuối 14:05" (số đo được, không hứa)'),
 ('Dấu gạch 350 chỗ', '" - "', '"–" có khoảng trắng cho vế/khoảng; "·" cho meta ngắn'),
 ('12 chỗ "anh"/"em"', '"VPS của anh", "em tính được số dư"', '"máy chủ của bạn", "hệ thống ước tính"'),
 ('Mascot', '"Hỏi em nè! 👋 … hay báo Zalo ạ?"', '"Cần hỗ trợ?" · "Tôi là trợ lý SmartLead — bạn cần giúp về quét nhóm, lead hay pipeline?"; bỏ chip Zalo'),
 ('fmtVnd', '"1,2 tr₫" / "3 tỷ₫"', '"1,2 triệu ₫" / "3 tỷ ₫" / "850.000 ₫" — 1 hàm dùng chung'),
 ('Ngày giờ', '12 biến thể', '1 fmtTime "14:05 · 07/09/2026"; khoảng "2 phút 15 giây"; tương đối vừa xong / 5 phút trước / hôm qua'),
 ('ALL CAPS gõ tay', '78 cụm', 'gõ sentence case + class .eyebrow (CSS uppercase)'),
 ('Chữ LỆNH/CF/v119', '"Rules audit_log chưa deploy (LỆNH #8)", "v119-42"', '"Tính năng chưa được bật — liên hệ Z15", "Nhật ký ghi từ 04/09/2026"'),
 ('"Super Admin"', '48 dòng', '"Quản trị hệ thống"; bỏ câu "Bạn là Super Admin"'),
 ('Ticker + hotline', 'placeholder ticker chiếm đầu trang; HOTLINE 24/7 pulse 2 chỗ', 'ẩn hẳn khi tắt (nút bật trong Cài đặt); hotline 1 chỗ, "Hỗ trợ" + giờ thật'),
]
RULES = [
 'Xưng hô: câu vô nhân xưng; bắt buộc thì "bạn". Không "anh/chị", "anh", "em", "ạ", "nhé" — trừ hộp chat trợ lý AI.',
 'Động từ thao tác: "bấm"; "chọn" chỉ cho dropdown/checkbox; bỏ "Hãy", "Vui lòng".',
 'Giữ tiếng Anh: lead, pipeline, brand, ROI, CRM, SLA, inbox, group/fanpage, AI. Việt hoá: từ khoá, chấm điểm, tự động, tài khoản FB (nick), máy chủ (worker/engine/VPS). LỆNH/CF/Rules/index tuyệt đối không hiện.',
 'Nhãn nav/tiêu đề/nút: sentence case, nav ≤3 từ, không emoji ở tiêu đề card & nút; 1 tên duy nhất cho 1 mục ở mọi nơi.',
 'Nhãn nhỏ (eyebrow): gõ sentence case, uppercase bằng CSS; không viết HOA nhấn mạnh giữa câu.',
 'Dấu câu: "–" (có khoảng trắng) cho vế/khoảng; "·" cho meta ≤3 mảnh; "…" 1 ký tự; "→" chỉ ở nút điều hướng.',
 'Toast: 1 câu ≤80 ký tự, kết thúc dấu chấm, bắt đầu bằng kết quả ("Đã lưu.", "Không lưu được — mất kết nối."); không mã lỗi, không tên hạ tầng, không "(demo)".',
 'Hộp thoại: modal của app; tiêu đề = hành động ("Xoá nguồn quét?"), nút chính = động từ; không confirm/prompt/alert.',
 'Số/tiền/giờ: vi-VN; "1,2 triệu ₫ / 850.000 ₫"; "HH:mm · dd/MM/yyyy"; tương đối "vừa xong / 5 phút trước / hôm qua"; % 1 số lẻ.',
 'Mô tả ≤90 ký tự, placeholder ≤50 (hướng dẫn dài → helper text), tooltip ≤90 và không chứa vận hành nội bộ; trạng thái hệ thống = số đo được, không lời hứa.',
]
