# -*- coding: utf-8 -*-
# Findings for "Rà soát UI SmartLead" — each: id, sev (cao/vua/thap), title, where, evidence (imgs), what, fix, effort
F = [
 dict(id='A', sev='cao', title='Lớp nổi che nội dung: mascot “Hỏi em nè! 👋” + nút chat + hotline',
  where='Mọi mục · rõ nhất trên mobile, tablet 768 và cuối trang dài',
  imgs=['m-feed','t-overview-768','d-outreach@bottom'],
  what='Bong bóng mascot + nút chat tròn nằm cố định góc phải dưới, hotline đỏ nổi góc trái dưới (≤1024px). Trên iPhone chúng đè lên số KPI, pill email trong thẻ lead, nút “Dừng tất cả” ở panel VPS (desktop cuộn cuối trang). Ba lớp nổi + thanh tab dưới = 4 thứ tranh nhau 25% màn hình.',
  fix='Giữ đúng 1 điểm nổi (nút chat) và thu về icon 48px không bong bóng; hotline chuyển vào trang Tài khoản/menu; đệm đáy `.view` ≥ chiều cao lớp nổi; ẩn lớp nổi khi modal/drawer mở (đã có) và khi bàn phím mobile bật.',
  effort='0,5 ngày'),
 dict(id='B', sev='cao', title='302 emoji dùng làm icon, trộn với bộ icon SVG',
  where='45-outreach 58 · 65-lead-modal 53 · 50-config 35 · 70-shell 32 · 20-feed 28 …',
  imgs=['d-alerts','d-modal-brandcfg2@center','d-modal-timeline@center'],
  what='Cùng một thanh công cụ vừa có icon SVG nét mảnh (SLI.*) vừa có emoji màu (✍️ ⚙️ 🎯 🔥 💬 🤖 🛡 ⛔). Emoji hiển thị khác nhau theo hệ điều hành (Windows/Android thường xấu hơn macOS), không đổi được màu, lệch baseline với chữ. Đây là dấu hiệu “vibe code” dễ nhận nhất.',
  fix='Quy ước: emoji chỉ xuất hiện trong nội dung người dùng nhập; mọi icon giao diện lấy từ bộ SVI (SLI) 1 nét 1,75px, 16/18px. Thay theo lô: nút/tiêu đề card/chip/toast/timeline (~120 chỗ có ý nghĩa, còn lại là ✓/✕ đổi sang SVG check/x).',
  effort='1,5 ngày'),
 dict(id='C', sev='cao', title='Chữ kỹ thuật/nội bộ lọt ra giao diện',
  where='Bảng brand, Tiếp cận, Content Studio, Người dùng, Cài đặt, modal Quét quá khứ, timeline lead',
  imgs=['d-agency','d-modal-content@center','d-modal-addnick@center'],
  what='Ví dụ: “Chạy LỆNH #17 (CF statsOnLead + backfill 35 ngày + Rules)”, “Cần backend LỆNH #34 + worker 2026-09-06c”, “Chưa cấu hình MANUAL_SCAN_URL”, “Điền nhanh theo thư viện ngành (v119-42)”, “Token cất ở Secret Manager qua Cloud Function”, cột “NICK / ACCOUNT_PID”, timeline “nick apk1gm6por”, “(UI demo - chưa nối backend)”, “cách ly brand được ép ở Firestore Rules”. Sales/khách đọc thấy = sản phẩm đang dở.',
  fix='Tách 2 lớp chữ: (1) người dùng — chỉ nói kết quả (“Số liệu đang ước tính, sẽ chính xác sau khi máy chủ đếm”); (2) chẩn đoán cho Super Admin — gom vào 1 khối “Chi tiết kỹ thuật” thu gọn hoặc console. Xoá mọi số phiên bản/LỆNH/tên function khỏi template.',
  effort='1 ngày'),
 dict(id='D', sev='cao', title='Trang và tính năng “giả”: Tích hợp, Cài đặt tài khoản, kênh Notion/Airtable/CRM',
  where='Tích hợp · Cài đặt tài khoản · Cảnh báo',
  imgs=['d-integrations','d-account'],
  what='“Tích hợp” là brochure tĩnh: Meta Graph API / n8n / Supabase với nút “Cấu hình →” không làm gì, banner nhắc “docs/HUONG-DAN-TICH-HOP-FACEBOOK.md trong gói”. Cài đặt tài khoản có “Thông báo cá nhân (UI demo - chưa nối backend)”, “Phiên & thiết bị (demo)”. Cảnh báo có công tắc Notion/Airtable/CRM chưa nối. Người dùng bấm thử → mất niềm tin.',
  fix='Gỡ khỏi menu những gì chưa chạy (Tích hợp → gộp kênh thật Zalo ZBS/Telegram/Sheet/Webhook vào Cảnh báo); Cài đặt tài khoản chỉ giữ: hồ sơ, đổi mật khẩu, thông báo đẩy, đăng xuất. Tính năng tương lai để “Sắp có” 1 dòng, không vẽ UI đầy đủ.',
  effort='0,5 ngày'),
 dict(id='E', sev='cao', title='Bảng điều khiển: màn hình đầu là widget quản trị, KPI rơi dưới fold',
  where='Bảng điều khiển (1440×900)',
  imgs=['f-overview','d-overview'],
  what='Thứ tự hiện tại: banner ticker → widget Quét tự động → widget Phương thức quét (4 ô xám) → Bảng brand → Bắt đầu → Hôm nay → KPI → chart. Ở laptop 900px, người dùng không thấy KPI/chart nào khi vừa vào. Hai widget quản trị lặp lại thông tin đã có trên topbar (AUTO/API).',
  fix='Sắp lại: Hôm nay (việc cần làm) → 4 KPI → chart/phân loại → Bảng brand (super) → nguồn/phễu. Gom 2 widget quản trị thành 1 dải trạng thái 1 dòng (“Quét tự động · Bright Data · lần cuối 03:46 · Đổi”) và banner ticker về Cài đặt.',
  effort='0,5 ngày'),
 dict(id='F', sev='vua', title='Topbar: chip “AUTO”/“API” khó hiểu, nút icon-only không nhãn trên mobile/tablet',
  where='Topbar mọi mục',
  imgs=['m-overview','t-overview-768'],
  what='“⏱ AUTO” và “🌐 API” là chip trạng thái nhưng trông như nút; sales không biết nghĩa. Mobile/tablet: “Quét quá khứ” và “Quét ngay” thành icon tròn không nhãn; ô tìm kiếm cụt “Tìm lead theo tên, nội dung, ng…”.',
  fix='Một chip trạng thái duy nhất có tooltip (“Quét tự động · Bright Data”), nút Quét ngay giữ chữ, Quét quá khứ vào menu ⋯; placeholder ngắn “Tìm lead, SĐT, email…”. Ẩn chip trạng thái cho vai sales.',
  effort='0,5 ngày'),
 dict(id='G', sev='vua', title='Sidebar: hotline + khối user chiếm đáy, giấu 8 mục Vận hành',
  where='Sidebar desktop ≤ 900px cao · drawer mobile',
  imgs=['m-drawer@bottom','t-users-1024@bottom'],
  what='Khối HOTLINE 24/7 (cao 60px) + khối user (70px) cố định đáy; danh sách mục phải cuộn bên trong. Drawer iPhone chỉ thấy tới “VẬN HÀNH” rồi hotline — 8 mục (Tiếp cận, Cảnh báo, Báo cáo…) ẩn. Khối brand ở đầu có viền gradient 3 màu lệch tông với phần còn lại.',
  fix='Hotline thành 1 dòng text nhỏ trong menu Tài khoản hoặc footer; nav 1 cột đủ 18 mục ở 844px với hàng 36px; viền brand card 1 màu.',
  effort='0,5 ngày'),
 dict(id='H', sev='vua', title='Bảng rộng bị cắt cột, không có dấu hiệu cuộn; số monospace chọi font',
  where='Bảng brand (11 cột) · Người dùng (6 nút/dòng) · Tiếp cận · Bài đã quét',
  imgs=['d-agency','d-users','d-reports'],
  what='Ở 1440px Bảng brand chỉ thấy 8/11 cột, hàng nút brand ở Người dùng mất nút cuối; không có bóng mờ/mũi tên báo còn cột. Số liệu dùng font monospace (`.mono`) khác font chữ → bảng trông như terminal; tiền tệ 3 kiểu ($0,0005 · trđ · đ).',
  fix='Bảng có `overflow-x:auto` + bóng mờ mép phải + cột đầu sticky; nút hàng gom vào menu ⋯ (giữ 2 nút chính); số dùng font chữ với `tabular-nums`; thống nhất tiền: VND “đ”, USD giữ “$” 2 số lẻ.',
  effort='1 ngày'),
 dict(id='I', sev='vua', title='Modal lead: form Đã chốt/Không thành bị thanh nút che; timeline lộ mã nick',
  where='Modal chi tiết lead',
  imgs=['d-modal-lead-bottom@center','d-modal-timeline@center'],
  what='Thanh nút dính đáy (`.ld-actions` sticky) che ~70px nội dung cuối — khi bấm “Không thành”, form hiện dưới thanh, phải cuộn mò. Nút chính dùng emoji ✅/✕/🔁/📵… Dòng timeline hiện “nick apk1gm6por” (mã kỹ thuật), giờ dùng font mono.',
  fix='`.modal-body` đệm đáy = chiều cao thanh nút; form Đã chốt/Không thành mở thành bước riêng trong modal (thay tại chỗ) hoặc cuộn tới đúng form; icon SVG; timeline hiện “nick Trang Beauty” (label) thay mã.',
  effort='0,5 ngày'),
 dict(id='J', sev='vua', title='Chữ nghĩa: mô tả dài, dấu câu lẫn lộn, trộn Anh–Việt, hộp thoại native',
  where='Toàn app',
  imgs=['d-tasks','d-scoring'],
  what='Dòng mô tả dưới tiêu đề/tên card thường 2–3 dòng, nhiều chỗ là hướng dẫn kỹ thuật (Scoring: “Cloud Scheduler”, “record BrightData”, “token AI”). Dùng “ - ” thay gạch ngang, “→” trong câu, chú giải kiểu “🚨 = leo thang (…)” ngay dưới tiêu đề. Tên mục lẫn tiếng Anh: “Lead feed realtime”, “Pipeline sales”, “Cấu hình AI Scoring”, “Bảng brand (agency)”. 15 `confirm()` + 7 `prompt()` native (hộp thoại trình duyệt, không có thương hiệu, tiếng Anh nút OK/Cancel).',
  fix='Bộ quy ước 10 dòng (tên mục, dấu câu, xưng hô, độ dài mô tả ≤ 90 ký tự; chi tiết → tooltip/“Tìm hiểu thêm”); hộp thoại xác nhận/nhập riêng của app (`slConfirm/slPrompt`) thay native.',
  effort='1 ngày'),
 dict(id='K', sev='vua', title='Mobile: KPI 1 cột quá cao, banner ticker chiếm đầu trang, header thẻ lead 3 dòng chip',
  where='iPhone 390px',
  imgs=['mt-outreach','m-feed'],
  what='Tiếp cận/Người dùng: 4 KPI xếp 1 cột, mỗi ô ~180px → cuộn 1 màn mới tới nội dung. Banner “Thanh thông báo đang tắt…” (cấu hình super) chiếm dòng đầu mọi trang. Thẻ lead: tên + Lead #10 + Nóng + chip Zalo + chip “Đăng ở 3 nơi” + giờ = 3 dòng trước khi thấy nội dung.',
  fix='KPI 2 cột trên mobile (số 28px); banner cấu hình chỉ hiện ở desktop super hoặc trong Cài đặt; header thẻ lead gom: hàng 1 tên + nhiệt độ + giờ, hàng 2 chip (tối đa 2, còn lại “+1”).',
  effort='0,5 ngày'),
 dict(id='L', sev='thap', title='Pipeline: chip “⏱ —” rỗng, nút hàng cuối gãy dòng, cột thứ 5 cắt không gợi ý cuộn',
  where='Pipeline sales',
  imgs=['d-pipeline'],
  what='Thẻ không có mốc thời gian vẫn vẽ chip “⏱ —”. Thẻ có 3 nút (Giao · Loại · Chi tiết) gãy “Chi tiết” xuống 2 dòng ở cột 250px. Kanban 7 cột chỉ thấy 4,5 cột, không bóng mờ mép phải; dòng gợi ý “Kéo-thả thẻ…” bị cắt.',
  fix='Ẩn chip khi không có dữ liệu; nút “Chi tiết” thành icon → hoặc click cả thẻ; bóng mờ mép phải + nút cuộn cột; gợi ý kéo-thả thành tooltip.',
  effort='0,25 ngày'),
 dict(id='M', sev='thap', title='Trạng thái rỗng/chờ/lỗi chưa có “component” chung',
  where='Feed rỗng, Phản hồi khách, Chờ duyệt, Chưa gán brand, banner kênh',
  imgs=['d-login-pending@center','d-replies'],
  what='Feed rỗng = 1 dòng chữ trong card; màn Chờ duyệt/Chưa gán brand dùng emoji 🕒 🏷️ cỡ lớn làm minh hoạ; Phản hồi khách 1 card rồi trống 80% màn.',
  fix='1 component `emptyState({icon, title, text, action})` (SVG 40px, 1 câu, 1 nút) dùng chung; trang ít nội dung thêm gợi ý việc tiếp theo.',
  effort='0,5 ngày'),
 dict(id='N', sev='thap', title='Nhất quán chi tiết: 2 kiểu ô AI, ALL-CAPS có dấu, input ngày native, nhãn “Super Admin” lặp',
  where='Lead feed, rail phải, Người dùng, wizard',
  imgs=['d-feed','d-modal-wizard1@center'],
  what='Thẻ lead có 2 hộp AI khác màu/nhãn (“AI · NHU CẦU TỔNG HỢP” cam vs “AI · ĐỌC VỊ NHU CẦU” xanh) cho cùng vai trò. Nhãn ALL-CAPS + letter-spacing với dấu tiếng Việt (“CHỜ GIAO XỬ LÝ”) khó đọc. Input ngày native hiện “mm/dd/yyyy” tuỳ trình duyệt. Chip “Super Admin” đỏ lặp trên nhiều card (6 chỗ ở Nguồn quét) — nên là 1 icon khoá nhỏ có tooltip.',
  fix='1 kiểu hộp AI (đổi icon theo loại); nhãn nhỏ dùng chữ thường đậm 12px thay caps; date picker của app hoặc text “dd/mm/yyyy” + mask; nhãn quyền thành icon.',
  effort='0,5 ngày'),
]
VIEWS = [
 ('Bảng điều khiển', 3, 'Thứ tự khối sai (E), 2 widget quản trị lặp topbar, ticker banner', 'E F'),
 ('Bảng brand', 3, 'Bảng 11 cột cắt, banner kỹ thuật LỆNH #17, số mono, sparkline rỗng', 'C H'),
 ('Lead feed', 4, 'Tốt nhất app; header thẻ 3 dòng chip trên mobile, 2 kiểu hộp AI, rail ALL-CAPS', 'K N'),
 ('Hộp việc', 3, 'Tiêu đề emoji 🎯👥💬🔥, chú giải 🚨 trong mô tả, “— chưa giao —”', 'B J'),
 ('Phản hồi khách', 2, 'Trang gần trống, mô tả kỹ thuật “Máy (Tiếp cận) đã DỪNG…”, chip ⏳', 'M J'),
 ('Pipeline sales', 3, 'Chip “⏱ —”, nút gãy dòng, cột cắt không gợi ý', 'L'),
 ('Giá trị & ROI', 4, 'Rõ ràng; đoạn “Phương pháp tính” dài, chip RIÊNG/CHUNG caps', 'J'),
 ('Nguồn quét', 3, 'Card so sánh 2 phương thức dài với emoji 🌐👤 to; 6 chip Super Admin', 'B N'),
 ('Keyword & bộ lọc', 4, 'Gọn; banner cuối dài', 'J'),
 ('Cấu hình AI Scoring', 2, 'Mô tả kỹ thuật dài nhất app, slider native, mono wrap 2 dòng, emoji tiêu đề', 'C J B'),
 ('Tiếp cận', 3, 'Dày đặc nhưng có cấu trúc; emoji nút ✍️⚙️, cột ACCOUNT_PID, bảng cắt, mascot đè nút', 'A B C H'),
 ('Cảnh báo', 2, 'Kênh Notion/Airtable/CRM giả, emoji dày, “cần token trong functions/.env”', 'D B C'),
 ('Báo cáo & tối ưu', 3, 'Tiền tệ $ với dấu phẩy, số mono, nút In OK', 'H'),
 ('Lịch sử quét', 3, 'Bảng mono, chi phí $0,0078', 'H'),
 ('Bài đã quét', 4, 'Dày nhưng đọc được; nhãn decision rõ', '—'),
 ('Tích hợp', 1, 'Trang placeholder, nút không hoạt động, banner docs/*.md', 'D'),
 ('Người dùng', 2, 'Đoạn hướng dẫn dài, 6 nút/dòng brand cắt, input mm/dd/yyyy, lộ email super, panel inline dài', 'C H J N'),
 ('Cài đặt tài khoản', 2, 'Khối “(demo)” chưa nối, bố cục hẹp khác các trang', 'D'),
]
QUESTIONS = [
 ('Mascot “Hỏi em nè!” + hotline', 'Giữ 1 nút chat nhỏ, bỏ bong bóng + hotline nổi (chuyển vào Tài khoản). Đây là chỗ anh từng chốt UI riêng nên em hỏi lại trước khi đụng.'),
 ('Emoji trong giao diện', 'Thay toàn bộ bằng icon SVG (giữ emoji trong nội dung khách/ghi chú). Nếu anh muốn giữ vài chỗ “vui” (chip 🔥 nóng), nói rõ chỗ nào.'),
 ('Trang Tích hợp + khối demo ở Cài đặt', 'Gỡ hẳn khỏi menu (kênh thật gom vào Cảnh báo) hay giữ với nhãn “Sắp có”?'),
 ('Tên mục Việt hoá', 'Đề xuất: Lead feed realtime → “Lead mới”, Pipeline sales → “Pipeline”, Cấu hình AI Scoring → “Chấm điểm AI”, Bảng brand (agency) → “Bảng brand”, Tiếp cận giữ, Bài đã quét giữ. Anh chốt danh sách.'),
 ('Thứ tự Bảng điều khiển', 'Hôm nay → KPI → chart → Bảng brand → nguồn/phễu; widget quản trị thành 1 dải 1 dòng. Đồng ý không?'),
]
