# FE v119-57 / v120-esm-g (06/09/2026): (1) wizard "Thêm brand mới" bước Hoàn tất có "🔎 Quét thử nguồn này (≤15 bài)" — chọn 1 nguồn của brand → openBackfill(url, tên,
# {numPosts:15, range:'7d'}) → manualScan mode backfill nhận sourceUrl + numPosts (backend đã hỗ trợ từ LỆNH #19) → xem chất lượng lead của riêng nguồn trước khi để tự động;
# (2) openBackfill nhận opts {numPosts, range} (tiêu đề + body.numPosts + rangeText); (3) live.js đọc content_stats/{brand} (CF statsOnLead — LỆNH #36) → D.contentStats;
# (4) card "📈 Hiệu quả nội dung" (Content Studio) ưu tiên counter máy chủ (chính xác mọi quy mô), chưa có counter → đếm lead đã nạp như v119-55; (5) smoke +3 check.
# Dùng: python3 fe57.py <root> iife|esm
import sys, os
root, mode = sys.argv[1], sys.argv[2]
def load(rel):
    p = os.path.join(root, rel); return p, open(p, encoding='utf-8').read()
def save(p, s): open(p, 'w', encoding='utf-8').write(s)
def R(s, a, b, n=1):
    assert s.count(a) == n, (a[:90], s.count(a)); return s.replace(a, b)

# ---------- 70-shell-tools: openBackfill(sourceUrl, sourceName, opts) ----------
p, s = load('src/app/70-shell-tools.js')
s = R(s, "  function openBackfill(sourceUrl, sourceName){\n    const fn=(window.SL_CONFIG&&window.SL_CONFIG.MANUAL_SCAN_URL)||'';",
       "  function openBackfill(sourceUrl, sourceName, opts){\n    opts=opts||{}; const quickN=Math.max(0,Math.min(100,Number(opts.numPosts)||0)); // v119-57: quét thử riêng nguồn (wizard) — giới hạn số bài + khoảng chọn sẵn\n    const fn=(window.SL_CONFIG&&window.SL_CONFIG.MANUAL_SCAN_URL)||'';")
s = R(s, "        <div class=\"sub\" style=\"margin-top:4px\">Phạm vi: <b>${target}</b></div></div>\n        <button class=\"close\" id=\"bfClose\">${SLI.x}</button></div>",
       "        <div class=\"sub\" style=\"margin-top:4px\">Phạm vi: <b>${target}</b>${quickN?' · <b>quét thử</b> tối đa '+quickN+' bài mới nhất':''}</div></div>\n        <button class=\"close\" id=\"bfClose\">${SLI.x}</button></div>")
s = R(s, "${ranges.map(([k,l])=>`<button data-range=\"${k}\" class=\"${k==='7d'?'active':''}\">${l}</button>`).join('')}",
       "${ranges.map(([k,l])=>`<button data-range=\"${k}\" class=\"${k===(opts.range||'7d')?'active':''}\">${l}</button>`).join('')}")
s = R(s, "    let range='7d';\n    const seg=modal.querySelector('#bfSeg'), custom=modal.querySelector('#bfCustom');",
       "    let range=opts.range||'7d';\n    const seg=modal.querySelector('#bfSeg'), custom=modal.querySelector('#bfCustom');")
s = R(s, "      if(sourceUrl) body.sourceUrl=sourceUrl;\n      if(!fn){ toast('Demo - cấu hình MANUAL_SCAN_URL để quét thật.'); closeModal(); return; }",
       "      if(sourceUrl) body.sourceUrl=sourceUrl;\n      if(quickN){ body.numPosts=quickN; rangeText+=' · quét thử '+quickN+' bài'; } // v119-57: backend scanAll(opts.numPosts) → fetchPosts numPosts\n      if(!fn){ toast('Demo - cấu hình MANUAL_SCAN_URL để quét thật.'); closeModal(); return; }")
save(p, s)

# ---------- 87-brand-wizard: bước Hoàn tất — quét thử 1 nguồn ----------
p, s = load('src/app/87-brand-wizard.js')
if mode == 'esm':
    s = R(s, "import { fold } from './70-shell-tools.js';", "import { fold, openBackfill } from './70-shell-tools.js';")
s = R(s, "      <div class=\"wz-actions\">\n        ${roleCanScan()?`<button class=\"btn btn-primary btn-sm\" id=\"wzScan\">${SLI.search} Quét ngay (mọi nguồn)</button>`:''}",
       "      ${(roleCanScan()&&srcAll.length)?`<div class=\"wz-try\"><span class=\"wz-small\">Quét thử riêng 1 nguồn (7 ngày gần nhất, tối đa 15 bài) để xem chất lượng lead trước khi để tự động:</span>\n        <select class=\"acs-in\" id=\"wzTrySrc\">${srcAll.map(s=>`<option value=\"${esc(s.url||'')}\">${esc(s.name||s.url||s.id||'')}</option>`).join('')}</select>\n        <button class=\"btn btn-soft btn-sm\" id=\"wzTryScan\">🔎 Quét thử nguồn này</button></div>`:''}\n      <div class=\"wz-actions\">\n        ${roleCanScan()?`<button class=\"btn btn-primary btn-sm\" id=\"wzScan\">${SLI.search} Quét ngay (mọi nguồn)</button>`:''}")
s = R(s, "    const sc=m.querySelector('#wzScan'); if(sc) sc.addEventListener('click',()=>{ wzClose(); const b=document.getElementById('scanBtn'); if(b) b.click(); else toast('Không thấy nút Quét ngay.'); });",
       "    const sc=m.querySelector('#wzScan'); if(sc) sc.addEventListener('click',()=>{ wzClose(); const b=document.getElementById('scanBtn'); if(b) b.click(); else toast('Không thấy nút Quét ngay.'); });\n    // v119-57: quét thử RIÊNG 1 nguồn của brand (backfill 7 ngày, numPosts 15) — manualScan nhận sourceUrl+numPosts (LỆNH #19); wizard đóng trước vì cùng dùng #modal\n    const ts=m.querySelector('#wzTryScan'); if(ts) ts.addEventListener('click',()=>{ const sel=m.querySelector('#wzTrySrc'); const url=sel&&sel.value; const nm=sel&&sel.options[sel.selectedIndex]?sel.options[sel.selectedIndex].textContent:''; if(!url){ toast('Nguồn chưa có link group.'); return; } wzClose(); openBackfill(url,nm,{numPosts:15,range:'7d'}); });")
save(p, s)

# ---------- CSS ----------
p, s = load('assets/css/app.css')
s = R(s, ".wz-actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 16px; }",
       ".wz-actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 16px; }\n.wz-try { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin-top: 14px; padding: 10px 12px; border: 1px dashed var(--line, #E9ECF7); border-radius: 12px; } /* v119-57: quét thử riêng nguồn */\n.wz-try .acs-in { max-width: 260px; }")
save(p, s)

# ---------- live.js: content_stats ----------
p, s = load('assets/js/live.js')
s = R(s, "  let sysStatus=null; // v119-50:", "  let contentStats={}; // v119-57: content_stats/{brand} — counter hiệu quả nội dung (sent/rep theo mode/parent/style/cta/variant) do CF statsOnLead cộng dồn (LỆNH #36) → card Content Studio chính xác mọi quy mô\n  let sysStatus=null; // v119-50:")
s = R(s, "d.sysStatus=sysStatus; // v119-50 trạng thái BrightData", "d.sysStatus=sysStatus; d.contentStats=contentStats; // v119-57 counter hiệu quả nội dung · v119-50 trạng thái BrightData")
s = R(s, "dailyStats=[]; dailyStatsErr=''; sysStatus=null;", "dailyStats=[]; dailyStatsErr=''; sysStatus=null; contentStats={};")
s = R(s, "        dataUnsub.push(onSnapshot(statsQ, snap=>{ chanOk('outreach_stats'); outreachStats={}; snap.forEach(d=>{ var x=d.data(); if(x.brandCode && x.day===tk) outreachStats[x.brandCode]=x; }); oaRepaint(); }, snapErr('outreach_stats'))); };",
       "        dataUnsub.push(onSnapshot(statsQ, snap=>{ chanOk('outreach_stats'); outreachStats={}; snap.forEach(d=>{ var x=d.data(); if(x.brandCode && x.day===tk) outreachStats[x.brandCode]=x; }); oaRepaint(); }, snapErr('outreach_stats')));\n        // v119-57: content_stats/{brand} — counter cộng dồn hiệu quả nội dung (CF statsOnLead, LỆNH #36). Rules có thể chưa deploy → lỗi chỉ console.warn (KHÔNG banner kênh), card tự rơi về đếm lead đã nạp.\n        var csQ = byBrand ? query(collection(db,'content_stats'), where('brandCode','==',byBrand)) : collection(db,'content_stats');\n        dataUnsub.push(onSnapshot(csQ, snap=>{ contentStats={}; snap.forEach(d=>{ var x=d.data()||{}; contentStats[x.brandCode||d.id]=x; }); oaRepaint(); }, function(e){ console.warn('[SL] content_stats', e&&e.code); })); };")
s = R(s, "      for(var j=0;j<codes.length;j++){ var st=outreachStats[codes[j]]||{}; s+='|'+codes[j]+'='+(st.react||0)+','+(st.comment||0)+','+(st.friend||0)+','+(st.inbox||0)+','+(st.replied||0); }\n      return s;",
       "      for(var j=0;j<codes.length;j++){ var st=outreachStats[codes[j]]||{}; s+='|'+codes[j]+'='+(st.react||0)+','+(st.comment||0)+','+(st.friend||0)+','+(st.inbox||0)+','+(st.replied||0); }\n      var cc=Object.keys(contentStats||{}).sort(); for(var q=0;q<cc.length;q++){ var ca=(contentStats[cc[q]]||{}).all||{}; s+='|cs:'+cc[q]+'='+(ca.sent||0)+','+(ca.rep||0)+','+(ca.tagged||0); } // v119-57\n      return s;")
save(p, s)

# ---------- 45-outreach: card ưu tiên counter ----------
p, s = load('src/app/45-outreach.js')
s = R(s, "  function csEffData(code) {\n    const all = (D.leads || [])",
       "  // v119-57: counter máy chủ content_stats/{brand} (CF statsOnLead — LỆNH #36: sent = lead có inbox_at, rep = lead đã inbox rồi phản hồi/chuyển Đã phản hồi trở đi) → chính xác mọi quy mô,\n  //   không phụ thuộc cửa sổ lead đã nạp. Khoá value dim đã \"làm sạch\" ở backend: variant → v0..v5 / vx (-1), parent rỗng → none; đổi ngược ở đây để dùng nhãn CS_META_VI.\n  const CS_KEY_BACK = { variant: k => (k === 'vx' ? '-1' : String(k).replace(/^v/, '')), parent: k => (k === 'none' ? '' : k) };\n  function csEffFromCounters(cs) {\n    const all = cs.all || {};\n    const dims = Object.keys(CS_META_VI).map(dim => {\n      const m = (cs[dim] && typeof cs[dim] === 'object') ? cs[dim] : {};\n      const rows = Object.keys(m).map(k => { const o = m[k] || {}; return { k: (CS_KEY_BACK[dim] || (x => x))(k), n: Number(o.sent) || 0, r: Number(o.rep) || 0 }; }).filter(x => x.n > 0)\n        .sort((a, b) => (b.r / b.n) - (a.r / a.n) || b.n - a.n).map(x => ({ label: CS_META_VI[dim][1][x.k] || x.k || '—', n: x.n, r: x.r }));\n      return { dim, title: CS_META_VI[dim][0], rows };\n    });\n    return { total: Number(all.sent) || 0, replied: Number(all.rep) || 0, dims, tagged: Number(all.tagged) || 0, server: true };\n  }\n  function csEffData(code) {\n    const cs = D.contentStats && D.contentStats[code]; if (cs && cs.all && Number(cs.all.sent) > 0) return csEffFromCounters(cs); // counter có số → tin máy chủ; chưa có → đếm lead đã nạp (v119-55)\n    const all = (D.leads || [])")
s = R(s, "    return `<div class=\"cs-preview cs-eff\" id=\"csEff\"><div class=\"cf-k\">📈 Hiệu quả nội dung <span class=\"muted\" style=\"font-weight:400;font-size:11px\">(lead đã nạp trên máy · phản hồi = máy phát hiện hoặc sales chuyển \"Đã phản hồi\" trở đi · mỗi dòng cần ≥30 tin mới đáng tin)</span></div>${body}</div>`;",
       "    return `<div class=\"cs-preview cs-eff\" id=\"csEff\" data-cs-src=\"${e.server ? 'server' : 'local'}\"><div class=\"cf-k\">📈 Hiệu quả nội dung <span class=\"muted\" style=\"font-weight:400;font-size:11px\">(${e.server ? 'máy chủ đếm cộng dồn - chính xác mọi quy mô' : 'lead đã nạp trên máy'} · phản hồi = máy phát hiện hoặc sales chuyển \"Đã phản hồi\" trở đi · mỗi dòng cần ≥30 tin mới đáng tin)</span></div>${body}</div>`;")
save(p, s)

# ---------- smoke: +3 check ----------
p, s = load('tools/smoke.js')
# (1) card đọc counter máy chủ
a = "    (/Chưa có tin inbox/.test(eff0) && eff1 && /Đã inbox 3/.test(eff1.sum) && /phản hồi 2/.test(eff1.sum) && eff1.rows >= 4) ? ok('v119-55: card Hiệu quả nội dung (rỗng → 3 tin/2 phản hồi, bảng theo bài gốc/CTA/biến thể)') : fail('v119-55 card hiệu quả sai: ' + JSON.stringify({ eff0: String(eff0).slice(0, 60), eff1 }));\n"
assert s.count(a) == 1
s = s.replace(a, a + "    /* v119-57: counter máy chủ content_stats (LỆNH #36) → card ưu tiên counter (data-cs-src=server), khoá variant/parent đổi ngược ra nhãn */\n    await page.evaluate(() => { const code = document.querySelector('button[data-oa-content]').dataset.oaContent; window.SL_DATA.contentStats = { [code]: { brandCode: code, all: { sent: 40, rep: 8, tagged: 55 }, mode: { ai: { sent: 30, rep: 7 }, reply: { sent: 10, rep: 1 } }, variant: { v0: { sent: 20, rep: 5 }, vx: { sent: 20, rep: 3 } }, parent: { none: { sent: 40, rep: 8 } }, cta: { brand: { sent: 40, rep: 8 } }, style: { direct: { sent: 40, rep: 8 } } } }; });\n    await page.click('button[data-oa-content]'); await page.waitForTimeout(300);\n    const eff2 = await page.evaluate(() => { const e = document.getElementById('csEff'); return e ? { src: e.dataset.csSrc, sum: (e.querySelector('.cs-eff-sum') || {}).textContent || '', rows: e.querySelectorAll('.cs-eff-t tbody tr').length, txt: e.textContent } : null; });\n    await page.evaluate(() => { const c = document.getElementById('csCancel'); if (c) c.click(); delete window.SL_DATA.contentStats; }); await page.waitForTimeout(200);\n    (eff2 && eff2.src === 'server' && /Đã inbox 40/.test(eff2.sum) && /phản hồi 8/.test(eff2.sum) && eff2.rows === 4 && /\\(không xoay\\)/.test(eff2.txt) && /Đồng cảm/.test(eff2.txt) && /máy chủ đếm/.test(eff2.txt)) ? ok('v119-57: card Hiệu quả nội dung đọc counter máy chủ (40 tin/8 phản hồi · 2 bảng · nhãn biến thể đổi ngược từ v0/vx)') : fail('v119-57 card counter sai: ' + JSON.stringify(eff2 && { src: eff2.src, sum: eff2.sum, rows: eff2.rows }));\n")
# (2) wizard Hoàn tất: ô chọn nguồn + nút quét thử (brand vừa tạo có 1 nguồn)
a = "  (wz7.step === 'done' && wz7.role === 'admin' && wz7.active && wz7.done === 6 && wz7.setup && wz7.scan) ? ok('Wizard: duyệt 1 user làm Quản trị → Hoàn tất 6/6 ✓ + nút Quét ngay + dấu setup') : fail('Hoàn tất sai: ' + JSON.stringify(wz7));\n"
assert s.count(a) == 1
s = s.replace(a, a + "  const wz7b = await page.evaluate(() => ({ opts: document.querySelectorAll('#wzTrySrc option').length, btn: !!document.getElementById('wzTryScan'), url: (document.querySelector('#wzTrySrc option') || {}).value }));\n  (wz7b.opts === 1 && wz7b.btn && /facebook\\.com\\/groups\\//.test(wz7b.url)) ? ok('v119-57: Hoàn tất có ô chọn nguồn (1 nguồn vừa tạo) + nút Quét thử nguồn này') : fail('v119-57 quét thử sai: ' + JSON.stringify(wz7b));\n")
# (3) resume z15 → tới Hoàn tất → bấm Quét thử → modal Quét ngược quá khứ phạm vi 1 nguồn, quét thử tối đa 15 bài, 7 ngày chọn sẵn
a = "  (rz3.step === 'users' && rz3.cold === 0 && rz3.on === true && rz3.crm) ? ok('Wizard resume: Lưu & tiếp KHÔNG đè ma trận tuỳ chỉnh, không tắt automation, không tách CRM khỏi cấu hình chung') : fail('Resume ghi đè: ' + JSON.stringify(rz3));\n  await page.keyboard.press('Escape'); await page.waitForTimeout(200);\n"
assert s.count(a) == 1
s = s.replace(a, "  (rz3.step === 'users' && rz3.cold === 0 && rz3.on === true && rz3.crm) ? ok('Wizard resume: Lưu & tiếp KHÔNG đè ma trận tuỳ chỉnh, không tắt automation, không tách CRM khỏi cấu hình chung') : fail('Resume ghi đè: ' + JSON.stringify(rz3));\n  await page.evaluate(() => { (window.SL_DATA.sources || []).slice(0, 2).forEach(s => { s.__bakBrand = s.brand; s.brand = 'z15'; }); }); // demo: nguồn không có brand → gán tạm 2 nguồn cho z15 (trả lại sau)\n  await page.click('#wzSkip'); await page.waitForTimeout(300);\n  const rz4 = await page.evaluate(() => { const n = (window.SL_DATA.sources || []).filter(x => (x.brand || '') === 'z15').length; return { step: document.querySelector('.wz-panel').dataset.wzStep, n, opts: document.querySelectorAll('#wzTrySrc option').length, btn: !!document.getElementById('wzTryScan') }; });\n  if (rz4.step === 'done' && rz4.n > 0 && rz4.opts === rz4.n && rz4.btn) { await page.click('#wzTryScan'); await page.waitForTimeout(300);\n    const rz5 = await page.evaluate(() => ({ h: (document.querySelector('#modal h3') || {}).textContent || '', sub: (document.querySelector('#modal .sub') || {}).textContent || '', run: !!document.getElementById('bfRun'), range: (document.querySelector('#bfSeg button.active') || { dataset: {} }).dataset.range, wz: !!document.querySelector('.wz-panel') }));\n    (/Quét ngược quá khứ/.test(rz5.h) && /quét thử/.test(rz5.sub) && /tối đa 15 bài/.test(rz5.sub) && rz5.run && rz5.range === '7d' && !rz5.wz) ? ok('v119-57: Quét thử nguồn này → modal quét ngược phạm vi 1 nguồn · quét thử tối đa 15 bài · 7 ngày chọn sẵn (wizard đã đóng)') : fail('v119-57 modal quét thử sai: ' + JSON.stringify(rz5));\n    await page.click('#bfClose'); await page.waitForTimeout(200);\n  } else { fail('v119-57: Hoàn tất (resume z15) thiếu ô quét thử: ' + JSON.stringify(rz4)); await page.keyboard.press('Escape'); await page.waitForTimeout(200); }\n  await page.evaluate(() => { (window.SL_DATA.sources || []).forEach(s => { if ('__bakBrand' in s) { if (s.__bakBrand === undefined) delete s.brand; else s.brand = s.__bakBrand; delete s.__bakBrand; } }); });\n")
save(p, s)
print('FE57 OK', mode)
